spring:
    application:
        name: GIPHY-SERVICE

server:
    port: 8083

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
    instance:
        hostname: localhost
        prefer-ip-address: true

giphy:
    api-key: Gc7131jiJuvI7IdN0HZ1D7nh0ow5BU6g